### ISSUE TITLE
Finding a new name for Chiissu

### ISSUE THREAD

**Issue by numbereddev** [Castyx/discussions#4]
### Discussed in https://github.com/orgs/ChiissuApp/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **MrSerge01** January 27, 2024</sup>
yes</div>

This is a very important discussion.

### Next, lets talk about this project's history.
This project was first founded in 2020 by me and a friend after my parents told me I should make a social media/chat app alternative to Twitter/WhatsApp, because they thought the privacy and bad UX of those apps were getting on their nerves as well as the privacy conditions these platforms have set.
I was told to make an app that also doesn't sacrifice on their original contacts, because they need that for several purposes.
Development went on untill around 2021-2022 and existed way before anything like Nebula or Chiissu was planned (back then I didn't even know what `Github` was).
Names changed for a bit, first it being `Chweppen`, but that didn't work due to it being based on a German accent which will be hard for English language speaking people. Then it's name was removed entirely and now I changed it's codename to `Chiissu`.
This name is **not** permanent.
Now in 2023/2024, I finally made a GitHub organisation for it and therefore needed some sort of (code-)name in order to set that.
Soo Tl;dr: This app/project existed way before the fabric of Nebula even started off, it's just now I started to write code for it again and rewrite it to Flutter and Zig.

**Comment by SwiftDust** [comment]
Really, I gave you more than 5 names to choose from. But to be honest with you, if you don't like those names, just go ahead and think of a name yourself. That is definitely NOT our responsibility. If you really can't come up with better ones yourself, that's fine. I want to think something out with you to help you get going, but you're the one that should take iniative. Just go ahead and shoot me a DM (@notabena Discord account, you know the drill)

**Comment by MrSerge01** [comment]
\> **fox**: hello! we are searching for new names
*we give suggestions*
*we're ignored*
\> **froxcey**: oh hey why do you still have the domain, can you give it back to me please
*gets ignored for months*
\> **fox**: hello! we are still searching for new names
*we remind of the names that we already suggested*
*we're ignored once again*
\> bruh moment

(why did chiissu.com get renewed)

**Comment by Starnt-xyz** [comment]
> Really, I gave you more than 5 names to choose from. But to be honest with you, if you don't like those names, just go ahead and think of a name yourself. That is definitely NOT our responsibility. If you really can't come up with better ones yourself, that's fine. I want to think something out with you to help you get going, but you're the one that should take iniative. Just go ahead and shoot me a DM (@notabena Discord account, you know the drill)



> > **fox**: hello! we are searching for new names _we give suggestions_ _we're ignored_ > **froxcey**: oh hey why do you still have the domain, can you give it back to me please _gets ignored for months_ > **fox**: hello! we are still searching for new names _we remind of the names that we already suggested_ _we're ignored once again_ > bruh moment
> 
> (why did chiissu.com get renewed)

I agree that ChiissuApp should be renamed, and please return a message to froxcey, it is extremely rude to ignore someone, if u are too scared to answer, then sungi should do it.

**Comment by numbereddev** [comment]
> \> **fox**: hello! we are searching for new names
> *we give suggestions*
> *we're ignored*
> \> **froxcey**: oh hey why do you still have the domain, can you give it back to me please
> *gets ignored for months*
> \> **fox**: hello! we are still searching for new names
> *we remind of the names that we already suggested*
> *we're ignored once again*
> \> bruh moment
> 
> (why did chiissu.com get renewed)

for one i those names were not rlly feasable especially cuz half those are not even available if i recall correctly and afaik i didnt ignore? i declined them

**Comment by numbereddev** [comment]
Domain has been given to Frox, but now how do we name this platform? Any proper ideas?

**Comment by Starnt-xyz** [comment]
> Domain has been given to Frox, but now how do we name this platform? Any proper ideas?

well let me propose this

the word social in korean translates to sahoeui if were talking sounds

so if u follow some basics u get

Sorii or Sorrii or Sori that is my idea

**Comment by numbereddev** [comment]
### We have following proposals
- Sorrii/Sori/Sorri - My opinion: sounds like sorry so could be misinterpreted but not bad
  - Pros: Easy to remember, Sorrii is available, sounds good, short
  - Neg: Negative SEO, could be confused with sorry
- Castyx (pronounced castix, both available but Castix is premium) - Comes from Broadcast/Cast to your friends
  - Pros: Unique, easy to remember, not easily associated with anything negative, available, positive SEO (y > i in ASCII)
  - Neg: The "y" could be confusing
- Saniboni: IsiZulu "hello y'all"
  - Pros: fits with the theme if yk background, sounds natural
  - Neg: Sounds a little too foreign, quite long for a name of a social platform
 
### About this platform
- Social Media
- Interactive - Creater -> User and User <-> User (Watch Parties, Music Wars, DMs, communities, posts, etc.)
- Primarily Video/Streaming, but also posts like Instagram and Twitter, too

### Name requirements
- Under 8 characters
- Needs to be pronouncable (without teaching) by English speakers primarily
- Should fit, not required to if a really good name

**Comment by numbereddev** [comment]
Decided on a name: https://castyx.com
